run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unused
    - misspell
    - gofmt

issues:
  exclude-use-default: false
  max-per-linter: 0
  max-same: 0
